/**
 * Generates docs/api/openapi.json and docs/api/endpoints.md from the Fastify route schemas.
 *
 *   npm run docs:api         write the files
 *   npm run docs:api:check   regenerate in memory and fail if the committed files differ
 *
 * Output is deterministic (sorted keys and routes, no timestamps) and run through Prettier
 * with the repo config, so `format:check` and `lint:md` accept it unchanged.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { format, resolveConfig } from 'prettier';

import { buildApp } from '../src/app.js';

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type Schema = { [key: string]: Json };

interface Parameter {
  name: string;
  in: string;
  required?: boolean;
  description?: string;
  schema?: Schema;
}

interface Operation {
  summary?: string;
  description?: string;
  tags?: string[];
  parameters?: Parameter[];
  requestBody?: { content?: Record<string, { schema?: Schema }> };
  responses?: Record<
    string,
    { description?: string; content?: Record<string, { schema?: Schema }> }
  >;
  security?: Record<string, string[]>[];
}

const repoRoot = path.resolve(import.meta.dirname, '../..');
const defaultOutDir = path.join(repoRoot, 'docs/api');
const methods = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options'];
const banner = '<!-- GENERATED by npm run docs:api — do not edit -->';

/** Recursively sorts object keys so the JSON diff only changes when the schema does. */
function sortKeys(value: Json): Json {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, sortKeys(value[key] ?? null)]),
    );
  }
  return value;
}

/** Escapes a value for a Markdown table cell. */
function cell(text: string | undefined): string {
  return (text ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ') || '—';
}

/** Short human-readable type for a JSON Schema node. */
function typeOf(schema: Schema | undefined): string {
  if (!schema) return 'unknown';
  if (Array.isArray(schema.enum)) return schema.enum.map((v) => JSON.stringify(v)).join(' | ');
  if ('const' in schema) return JSON.stringify(schema.const);
  for (const key of ['anyOf', 'oneOf'] as const) {
    const options = schema[key];
    if (Array.isArray(options)) return options.map((s) => typeOf(s as Schema)).join(' | ');
  }
  if (schema.type === 'array') return `${typeOf(schema.items as Schema)}[]`;
  if (Array.isArray(schema.type)) return schema.type.join(' | ');
  return typeof schema.type === 'string' ? schema.type : 'unknown';
}

/** Flattens an object schema into `field | type | required | description` rows (dotted paths). */
function fieldRows(schema: Schema | undefined, prefix = ''): string[] {
  const properties = schema?.properties as Record<string, Schema> | undefined;
  if (!properties)
    return [
      `| ${cell(prefix || '(body)')} | \`${typeOf(schema)}\` | yes | ${cell(schema?.description as string)} |`,
    ];
  const required = new Set((schema?.required as string[] | undefined) ?? []);
  return Object.keys(properties)
    .sort()
    .flatMap((name) => {
      const child = properties[name] ?? {};
      const field = prefix ? `${prefix}.${name}` : name;
      const row = `| \`${field}\` | \`${cell(typeOf(child))}\` | ${required.has(name) ? 'yes' : 'no'} | ${cell(child.description as string)} |`;
      return child.properties ? [row, ...fieldRows(child, field)] : [row];
    });
}

function schemaTable(schema: Schema | undefined): string {
  return [
    '| Field | Type | Required | Description |',
    '| --- | --- | --- | --- |',
    ...fieldRows(schema),
  ].join('\n');
}

function renderOperation(
  method: string,
  url: string,
  op: Operation,
  globalSecurity: Operation['security'],
): string {
  const lines = [`## \`${method.toUpperCase()} ${url}\``, ''];
  if (op.summary) lines.push(op.summary.endsWith('.') ? op.summary : `${op.summary}.`, '');
  if (op.description) lines.push(op.description, '');
  if (op.tags?.length) lines.push(`Tags: ${op.tags.map((t) => `\`${t}\``).join(', ')}`, '');

  const security = op.security ?? globalSecurity ?? [];
  const schemes = security.flatMap((requirement) => Object.keys(requirement));
  lines.push(
    `Auth: ${schemes.length ? schemes.map((s) => `\`${s}\``).join(', ') : 'none (public)'}`,
    '',
  );

  const params = [...(op.parameters ?? [])].sort((a, b) =>
    `${a.in}${a.name}`.localeCompare(`${b.in}${b.name}`),
  );
  if (params.length) {
    lines.push(
      '### Parameters',
      '',
      '| Name | In | Type | Required | Description |',
      '| --- | --- | --- | --- | --- |',
    );
    for (const p of params) {
      lines.push(
        `| \`${p.name}\` | ${p.in} | \`${cell(typeOf(p.schema))}\` | ${p.required ? 'yes' : 'no'} | ${cell(p.description ?? (p.schema?.description as string))} |`,
      );
    }
    lines.push('');
  }

  const body = op.requestBody?.content?.['application/json']?.schema;
  if (body) lines.push('### Request body', '', schemaTable(body), '');

  lines.push('### Responses', '');
  for (const status of Object.keys(op.responses ?? {}).sort()) {
    const response = op.responses?.[status];
    lines.push(`#### ${status}`, '');
    if (response?.description) lines.push(response.description, '');
    const schema = response?.content?.['application/json']?.schema;
    if (schema) lines.push(schemaTable(schema), '');
  }
  return lines.join('\n');
}

async function render(): Promise<Record<string, string>> {
  const app = await buildApp();
  await app.ready();
  const spec = app.swagger() as unknown as {
    info: { title: string; version: string };
    paths?: Record<string, Record<string, Operation>>;
    security?: Operation['security'];
  };
  await app.close();

  const sections: string[] = [];
  for (const url of Object.keys(spec.paths ?? {}).sort()) {
    const item = spec.paths?.[url] ?? {};
    for (const method of methods) {
      const op = item[method];
      if (op) sections.push(renderOperation(method, url, op, spec.security));
    }
  }

  const markdown = [
    banner,
    '',
    `# ${spec.info.title} endpoints`,
    '',
    `Version ${spec.info.version}. Generated from the Fastify route schemas in \`backend/src/routes/\`; the machine-readable spec is [openapi.json](openapi.json). To change this file, change the schema and run \`npm run docs:api\`.`,
    '',
    ...sections,
  ].join('\n');

  const files: Record<string, string> = {
    'openapi.json': JSON.stringify(sortKeys(spec as unknown as Json)),
    'endpoints.md': markdown,
  };
  for (const [name, text] of Object.entries(files)) {
    const filepath = path.join(defaultOutDir, name);
    const config = (await resolveConfig(filepath)) ?? {};
    files[name] = await format(text, { ...config, filepath });
  }
  return files;
}

const files = await render();

if (process.argv.includes('--check')) {
  const stale: string[] = [];
  for (const [name, text] of Object.entries(files)) {
    const current = await readFile(path.join(defaultOutDir, name), 'utf8').catch(() => null);
    if (current !== text) stale.push(path.relative(repoRoot, path.join(defaultOutDir, name)));
  }
  if (stale.length) {
    console.error(`API docs are stale, run \`npm run docs:api\`. Out of date: ${stale.join(', ')}`);
    process.exit(1);
  }
  console.log('API docs are up to date.');
} else {
  await mkdir(defaultOutDir, { recursive: true });
  for (const [name, text] of Object.entries(files)) {
    await writeFile(path.join(defaultOutDir, name), text);
    console.log(`wrote ${path.relative(repoRoot, path.join(defaultOutDir, name))}`);
  }
}
